[build]
  command = "echo 'No build step needed for PHP'"
  publish = "."

[build.environment]
  PHP_VERSION = "8.1"

# 确保PHP文件被正确处理
[[headers]]
  for = "*.php"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

# 处理所有请求到index.php
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[dev]
  command = "php -S localhost:8888"
